#!/bin/bash
tar -xf mock3.tar
dnf install httpd -y
systemctl enable --now httpd
firewall-cmd  --permanent --add-service=http
firewall-cmd --reload
cp webcontents/*  /var/www/html/
systemctl restart httpd
wget localhost/s
sh s

rm -rvf mock3
echo "Script is Ended"
echo "ALL the Very BEST!!!!"
